language: eiffel
before_script:
  - export current_dir=$PWD ; echo current_dir=$current_dir ; cd ..
  - export ISE_PLATFORM=linux-x86-64
  - curl -sSL https://www.eiffel.org/setup/install.sh | bash > eiffel.rc
  - source ./eiffel.rc
  - echo `ec -version`
  - cd $current_dir

# safelist
branches:
  only:
  - master
  - develop

script: 
  #compile code  
  - compile_all -ecb -melt -list_failures -log_verbose -clean -options dotnet=false
  #testing
  - ec -config test/test_suite.ecf -c_compile -tests 
